ALTER TABLE projects ADD COLUMN IF NOT EXISTS object_address TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS object_type TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS object_area TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_duration TEXT NOT NULL DEFAULT '';
